/**
 * Shared icons for the application
 *
 * This file exports commonly used icons from React Icons library
 * for consistent usage throughout the application.
 */

// Font Awesome Icons
import {
  FaUser,
  FaUsers,
  FaUserPlus,
  FaUserEdit,
  FaUserCog,
  FaEnvelope,
  FaLock,
  FaKey,
  FaSignInAlt,
  FaSignOutAlt,
  FaHome,
  FaCog,
  FaBell,
  FaCalendar,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarPlus,
  FaClock,
  FaSearch,
  FaPlus,
  FaMinus,
  FaEdit,
  FaTrash,
  FaSave,
  FaCheck,
  FaTimes,
  FaExclamationCircle,
  FaInfoCircle,
  FaQuestionCircle,
  FaArrowRight,
  FaArrowLeft,
  FaEllipsisV,
  FaBars,
  FaChevronDown,
  FaChevronUp,
  FaChevronLeft,
  FaChevronRight,
} from "react-icons/fa";

// Material Design Icons
import {
  MdDashboard,
  MdSettings,
  MdNotifications,
  MdPerson,
  MdMenu,
  MdClose,
  MdAdd,
  MdRemove,
  MdEdit,
  MdDelete,
  MdSave,
  MdCheck,
  MdCancel,
  MdSearch,
  MdInfo,
  MdWarning,
  MdError,
  MdHelp,
  MdArrowBack,
  MdArrowForward,
  MdMoreVert,
  MdExpandMore,
  MdExpandLess,
  MdChevronLeft,
  MdChevronRight,
} from "react-icons/md";

// Heroicons (Outline)
import {
  HiOutlineUser,
  HiOutlineMail,
  HiOutlineLockClosed,
  HiOutlineHome,
  HiOutlineCog,
  HiOutlineBell,
  HiOutlineCalendar,
  HiOutlineClock,
  HiOutlineSearch,
  HiOutlinePlus,
  HiOutlineMinus,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineSave,
  HiOutlineCheck,
  HiOutlineX,
  HiOutlineExclamation,
  HiOutlineInformationCircle,
  HiOutlineQuestionMarkCircle,
  HiOutlineArrowRight,
  HiOutlineArrowLeft,
  HiOutlineDotsVertical,
  HiOutlineMenu,
  HiOutlineChevronDown,
  HiOutlineChevronUp,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
} from "react-icons/hi";

// Export all icons
export {
  // Font Awesome
  FaUser,
  FaUsers,
  FaUserPlus,
  FaUserEdit,
  FaUserCog,
  FaEnvelope,
  FaLock,
  FaKey,
  FaSignInAlt,
  FaSignOutAlt,
  FaHome,
  FaCog,
  FaBell,
  FaCalendar,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarPlus,
  FaClock,
  FaSearch,
  FaPlus,
  FaMinus,
  FaEdit,
  FaTrash,
  FaSave,
  FaCheck,
  FaTimes,
  FaExclamationCircle,
  FaInfoCircle,
  FaQuestionCircle,
  FaArrowRight,
  FaArrowLeft,
  FaEllipsisV,
  FaBars,
  FaChevronDown,
  FaChevronUp,
  FaChevronLeft,
  FaChevronRight,

  // Material Design
  MdDashboard,
  MdSettings,
  MdNotifications,
  MdPerson,
  MdMenu,
  MdClose,
  MdAdd,
  MdRemove,
  MdEdit,
  MdDelete,
  MdSave,
  MdCheck,
  MdCancel,
  MdSearch,
  MdInfo,
  MdWarning,
  MdError,
  MdHelp,
  MdArrowBack,
  MdArrowForward,
  MdMoreVert,
  MdExpandMore,
  MdExpandLess,
  MdChevronLeft,
  MdChevronRight,

  // Heroicons
  HiOutlineUser,
  HiOutlineMail,
  HiOutlineLockClosed,
  HiOutlineHome,
  HiOutlineCog,
  HiOutlineBell,
  HiOutlineCalendar,
  HiOutlineClock,
  HiOutlineSearch,
  HiOutlinePlus,
  HiOutlineMinus,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineSave,
  HiOutlineCheck,
  HiOutlineX,
  HiOutlineExclamation,
  HiOutlineInformationCircle,
  HiOutlineQuestionMarkCircle,
  HiOutlineArrowRight,
  HiOutlineArrowLeft,
  HiOutlineDotsVertical,
  HiOutlineMenu,
  HiOutlineChevronDown,
  HiOutlineChevronUp,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
};
